name: 'Release .deb files'
on: release

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names:
          - base_image: "ubuntu:focal"
            image_name: "focal"
          - base_image: "debian:buster"
            image_name: "buster"
    steps:
      - uses: actions/checkout@v1
      - name: docker build with arg
        run: |
          mkdir -p $(pwd)/${{ matrix.names.image_name }}
          docker build --build-arg base_image=${{ matrix.names.base_image }} -t ${{ matrix.names.image_name }} -f packaging/Dockerfile .
          docker run --rm --mount "type=bind,source=$(pwd)/${{ matrix.names.image_name }},target=/packaging/output" ${{ matrix.names.image_name }}
          zip -r libsxg-${{ matrix.names.image_name }}.zip $(pwd)/${{ matrix.names.image_name }}

      - name: Upload to release
        uses: kumagi/upload-to-release@v0.1.2
        with:
          args: libsxg-${{ matrix.names.image_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
